# Generated by Django 5.1 on 2025-12-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_order_created_by_table_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='table',
            name='updated_at',
        ),
    ]
