# Generated by Django 5.1 on 2025-12-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0003_remove_bill_created_at_remove_table_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('kitchen', 'In Kitchen'), ('served', 'Served'), ('completed', 'Completed')], default='placed', max_length=20),
        ),
    ]
